---

- hosts: database
  remote_user: root
  become: yes

  tasks:
    - name: installation
      apt:
        #update_cache: yes
        name: [
          'aptitude',
          'vim',
          'mycli',
          'mytop',
          'htop',
          'curl',
          'htop',
          'net-tools',
          'mysql-client'
        ]

    - name: Install mariadb-server
      command: apt install -y mariadb-server

    - name: Restart service mariadb, in all cases
      service:
        name: mysql
        state: restarted

    - name: change root password
      command:  mysql -e " UPDATE  mysql.user set host = '%'  WHERE user = 'root'; flush privileges ;"
      ignore_errors: yes

    - name: change root password
      command:  mysql -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'bb';"
      ignore_errors: yes

    - name: change root password
      command:  mysql -e " GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'bb' WITH GRANT OPTION;"
      ignore_errors: yes