---

- hosts: web
  remote_user: root
  become: yes
  environment:
    MY_ENV_VARIABLE: whatever_value

  tasks:
    - name: installation
      apt:
        #update_cache: yes
        name: [
          'aptitude',
          'vim',
          'htop',
          'nmap',
          'apache2',
          'curl',
          'net-tools',
          'php7.2-fpm',
          'php7.2',
          'php7.2-mysql',
          'php7.2-cli',
          'php7.2-curl',
          'php-xdebug',
          'libapache2-mod-php',
          'mycli',
          'mysql-client',
          'composer',
          'git',
          'libnss3-tools'
        ]

#    - name: Run
#      command: wget https://github.com/FiloSottile/mkcert/releases/download/v1.1.2/mkcert-v1.1.2-linux-amd64
#
#
#    - name: Run
#      command: mv mkcert-v1.1.2-linux-amd64 mkcert
#
#
#    - name: Run
#      command: chmod +x mkcert
#
#
#    - name: Run
#      command: cp mkcert /usr/local/bin/
#
#    - name: Run
#      command: mkcert -install



    - name: Remove a file, if present
      file:
        path: /var/www/html/index.html
        state: absent
#
#    - name: Copy certificate script
#      copy:
#        src: usr/local/bin/generate-certificate.sh
#        dest: /usr/local/bin/generate-certificate.sh


    - name: Copy vars
      copy:
        src: etc/apache2/conf-enabled/vars.conf
        dest: /etc/apache2/conf-enabled/vars.conf

    - name: Copy vars
      copy:
        src: etc/apache2/sites-available/default-ssl.conf
        dest: /etc/apache2/sites-available/default-ssl.conf


    - name: Copy crt
      copy:
        src: etc/ssl/certs/localhost.pem
        dest: /etc/ssl/certs/localhost.pem

    - name: Copy key
      copy:
        src: etc/ssl/certs/localhost-key.pem
        dest: /etc/ssl/certs/localhost-key.pem

    - name: install mods
      apache2_module: state=present name=ssl

    - name: Copy php.ini
      copy:
        src: etc/php/7.2/fpm/php.ini
        dest: /etc/php/7.2/fpm/php.ini

    - name: Enable default SSL virtualhost
      become: yes
      command: "a2ensite default-ssl"


    - name: Restart service httpd, in all cases
      service:
        name: apache2
        state: restarted

    - name: Recursively change ownership of a directory
      file:
        path: /var/www
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Composer install
      composer:
        command: install
        working_dir: /var/www/html


    - name: Run
      command: curl localhost