---

- hosts: tomcat
  remote_user: root
  become: yes

  tasks:
#    - name: installation
#      apt:
#        update_cache: yes
#        name: [
#          'aptitude',
#          'vim',
#          'curl',
#          'maven',
#          'openjdk-8-jdk',
#          'tomcat9',
#          'tomcat9-examples',
#
#        ]
#    - name: Restart service tomcat9, in all cases
#      service:
#        name: tomcat9
#        state: restarted

    - name: Copy Hello.java
      copy:
        src: root/Hello.java
        dest: /root/Hello.java

    - name: Run
      command: javac /root/Hello.java

    - name: Run ls.sh and output "ls /"
      command: java -cp "/root/"  Hello
      register: out

    - debug: var=out.stdout_lines