---

- hosts: web
  remote_user: root
  become: yes

  tasks:
    - name: installation
      apt:
        update_cache: yes
        name: ['aptitude',
               'vim',
               'htop',
               'nmap',
               'apache2',
               'curl',
               'net-tools',
               'php7.2-fpm',
               'php7.2',
               'libapache2-mod-php'
        ]

    - name: Restart service httpd, in all cases
      service:
        name: apache2
        state: restarted

- hosts: database
  remote_user: root
  become: yes

  tasks:
    - name: installation
      apt:
        update_cache: yes
        name: [
          'aptitude',
          'vim',
          'mariadb-server',
          'mycli',
          'mytop','htop',
          'curl'
        ]
    - name: Restart service mariadb, in all cases
      service:
        name: mysql
        state: restarted