---

- hosts: web
  remote_user: root
  become: yes
  environment:
    MY_ENV_VARIABLE: whatever_value

  tasks:
    - name: installation
      apt:
        #update_cache: yes
        name: [
          'aptitude',
           'vim',
           'htop',
           'nmap',
           'apache2',
           'curl',
           'net-tools',
           'php7.2-fpm',
           'php7.2',
           'libapache2-mod-php',
           'mycli'
        ]

    - name: Remove a file, if present
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy vars
      copy:
        src: etc/apache2/conf-enabled/vars.conf
        dest: /etc/apache2/conf-enabled/vars.conf

    - name: Restart service httpd, in all cases
      service:
        name: apache2
        state: restarted

    - name: Recursively change ownership of a directory
      file:
        path: /var/www
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Run
      command: curl localhost