---

- hosts: web
  remote_user: root
  become: yes

  tasks:
    - name: installation
      apt:
        update_cache: yes
        name: ['aptitude',
               'vim',
               'htop',
               'nmap',
               'apache2',
               'curl',
               'net-tools',
               'php7.2-fpm',
               'php7.2'
        ]
    - name: Start
      become: yes
      service: name=apache2 state=started enabled=true

- hosts: database
  remote_user: root
  become: yes

  tasks:
    - name: installation
      apt:
        update_cache: yes
        name: ['aptitude',
               'vim'
        ]