---

- hosts: database
  remote_user: root
  become: yes

  tasks:
    - name: installation
      apt:
        update_cache: yes
        name: [
          'aptitude',
          'vim',
          'mysql-server',
          'mycli',
          'mytop','htop',
          'curl'
        ]
    - name: Restart service mariadb, in all cases
      service:
        name: mysql
        state: restarted